#!/bin/bash

all:
# 	LANG="en_US.utf8" lualatex -shell-escape 0_codifica.tex
# 	LANG="en_US.utf8" lualatex -shell-escape 1_introduction.tex
# 	LANG="en_US.utf8" lualatex -shell-escape 2_FP.tex
# 	LANG="en_US.utf8" lualatex -shell-escape 3_circuits_comb
# 	LANG="en_US.utf8" lualatex -shell-escape 4_circuits_seq.tex
	LANG="en_US.utf8" lualatex -shell-escape 5_openquestions.tex

clean:
	rm -f *.log *.aux *.png.enc *.png.png *.pdf *.xml

